// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/dushixiang/pika/internal/config"
	"github.com/dushixiang/pika/internal/handler"
	"github.com/dushixiang/pika/internal/service"
	"github.com/dushixiang/pika/internal/websocket"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp(logger *zap.Logger, db *gorm.DB, cfg *config.AppConfig) (*AppComponents, error) {
	userService := service.NewUserService(logger, cfg)
	oidcService := service.NewOIDCService(logger, cfg)
	gitHubOAuthService := service.NewGitHubOAuthService(logger, cfg)
	accountService := service.NewAccountService(logger, userService, oidcService, gitHubOAuthService, cfg)
	accountHandler := handler.NewAccountHandler(accountService)
	apiKeyService := service.NewApiKeyService(logger, db)
	agentService := service.NewAgentService(logger, db, apiKeyService)
	manager := websocket.NewManager(logger)
	monitorService := service.NewMonitorService(logger, db, manager)
	agentHandler := handler.NewAgentHandler(logger, agentService, monitorService, manager)
	apiKeyHandler := handler.NewApiKeyHandler(logger, apiKeyService)
	propertyService := service.NewPropertyService(logger, db)
	notifier := service.NewNotifier(logger)
	alertService := service.NewAlertService(logger, db, propertyService, notifier)
	alertHandler := handler.NewAlertHandler(logger, alertService)
	propertyHandler := handler.NewPropertyHandler(logger, propertyService, notifier)
	monitorHandler := handler.NewMonitorHandler(logger, monitorService)
	appComponents := &AppComponents{
		AccountHandler:  accountHandler,
		AgentHandler:    agentHandler,
		ApiKeyHandler:   apiKeyHandler,
		AlertHandler:    alertHandler,
		PropertyHandler: propertyHandler,
		MonitorHandler:  monitorHandler,
		AgentService:    agentService,
		AlertService:    alertService,
		PropertyService: propertyService,
		MonitorService:  monitorService,
		ApiKeyService:   apiKeyService,
		WSManager:       manager,
	}
	return appComponents, nil
}

// wire.go:

// AppComponents 应用组件
type AppComponents struct {
	AccountHandler  *handler.AccountHandler
	AgentHandler    *handler.AgentHandler
	ApiKeyHandler   *handler.ApiKeyHandler
	AlertHandler    *handler.AlertHandler
	PropertyHandler *handler.PropertyHandler
	MonitorHandler  *handler.MonitorHandler

	AgentService    *service.AgentService
	AlertService    *service.AlertService
	PropertyService *service.PropertyService
	MonitorService  *service.MonitorService
	ApiKeyService   *service.ApiKeyService

	WSManager *websocket.Manager
}
